version: '3.8'

services:
  voice-nav:
    build: .
    container_name: voice-nav-debug
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
      - ./src:/app/src  # Pour le développement en direct
    environment:
      - OPENCAGE_API_KEY=${OPENCAGE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    ports:
      - "5002:5000"
    # Suppression de la ligne devices pour macOS
    # devices:
    #   - "/dev/snd:/dev/snd"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"